server:
  port: 8110
  
spring:
  profiles:
    active: dev
  application:
    name: FireAdmin
  security:
    user:
      name: "admin"
      password: "admin"
  mail:
    host: smtp.163.com
    username: fire
    password: huo
  boot:
    admin:
      notify:
        mail:
          to: huo@fire.com

eureka:
  enabled: true
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10 #定期心跳
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    enabled: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://fire:huo@registrationcenter.fire.com:8761/eureka
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 3000
  environment: fire

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
  file:
    name: /opt/fire/admin/logs/log.log
    path: /opt/fire/admin/logs


